### ISSUE TITLE
Fails to install in FULL Sandbox for ALL Users

### ISSUE THREAD

**Issue by WadeLovell** [forcedotcom/AuraEnabledScanner#4]
Apex compile failure | Apex class deleteBuyerRecs_Test: line 43, column 42: Constructor not defined: [deleteBuyerCategoryRecs_US].<Constructor>()
-- | --
Apex compile failure | Apex class scheduledDeleteBuyerRecs_US: line 3, column 57: Constructor not defined: [deleteBuyerCategoryRecs_US].<Constructor>()

**Comment by tylerclark** [comment]
Hi @WadeLovell! That is a problem with one of your classes during the validation check on install. Try commenting out that file and see if that fixes it. You can verify our package is working properly by installing in a scratch org first.
