### ISSUE TITLE
Test failure for OE_Scanner_Test since Winter '21 security updates

### ISSUE THREAD

**Issue by maelmonnier** [forcedotcom/AuraEnabledScanner#5]
In our french environment, we have a test failure on our sandboxes on the class OE_Scanner_Test for shouldAcknowledgeIfUserHasScannerPermSet method. It appears to come from OE_Scanner_TestUtils.getStandardUserProfile.

Class : OE_Scanner_Test
Method : shouldAcknowledgeIfUserHasScannerPermSet

System.QueryException: List has no rows for assignment to SObject
Class.OE_Scanner_TestUtils.getProfile: line 25, column 1
Class.OE_Scanner_TestUtils.getStandardUserProfile: line 19, column 1
Class.OE_Scanner_TestUtils.createStandardUser: line 14, column 1
Class.OE_Scanner_Test.shouldAcknowledgeIfUserHasScannerPermSet: line 12, column 1

It is this SOQL query which failed : `SELECT Id FROM Profile WHERE Name = :name`. In `name` variable, we have `Standard User` but in french it is `Utilisateur standard`.

**Comment by dcstuff** [comment]
@maelmonnier Fixed! Apologies for the delay!
Diff here: https://github.com/forcedotcom/AuraEnabledScanner/commit/0c0b0a3e06219b55655ea78b2caea6e557d1dea0
