### ISSUE TITLE
Prod Install Question

### ISSUE THREAD

**Issue by sjo2020** [forcedotcom/AuraEnabledScanner#9]
When installing to production I get a pop up in re: Apex Compile. What essentially is this doing? Is it doing a full compile of everything pre-existing in my org if I keep the default vs if I select the 'only apex in the package' it only compiles what comes across just with the package? 

![Screen Shot 2020-10-27 at 1 44 24 PM](https://user-images.githubusercontent.com/73491919/97347313-9cb28300-185a-11eb-972f-ec2efc174bf0.png)

**Comment by dcstuff** [comment]
Correct
